name: 部署文档

on:
  push:
    branches:
      - doc/v3
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装 pnpm
        run: |
          npm install -g pnpm

      - name: 安装依赖
        run: 
          pnpm install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          
      - name: 部署文档
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.ALI_SERVER_HOST }}
          user: ${{ secrets.ALI_SERVER_NAME }}
          pass: ${{ secrets.ALI_SERVER_PASSWD }}
          connect_timeout: 100s
          local: './src/.vuepress/dist/*'
          remote: ${{ secrets.ALI_TARGET_v3 }}
